### ISSUE TITLE
Integration does not start under new HA 2026.9.0

### ISSUE THREAD

**Issue by isi07** [pail23/stiebel_eltron_isg_component#678]
### Before reporting

- [x] I searched the existing issues and discussions
- [x] I am running the latest version of the integration, or I state below why not

### Integration version

2026.8

### Home Assistant version

2026.9.0

### Detected controller

LWZ

### Heat pump model

LWZ 403 SOL

### What happened, and what did you expect instead

after installation of new HA Version 2026.9.0 th integration does not start any more

I have the following in the logs

```
Logger: homeassistant.util.loop
Quelle: util/loop.py:75
Erstmals aufgetreten: 19:51:06 (1 Vorkommnis)
Zuletzt protokolliert: 19:51:06

Detected blocking call to import_module with args ('custom_components.stiebel_eltron_isg',) in /usr/src/homeassistant/homeassistant/loader.py, line 1095: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 203, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 280, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.14/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 2056, in _run_once handle._run() File "/usr/local/lib/python3.14/asyncio/events.py", line 94, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 341, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1047, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1095, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
```

```
Logger: homeassistant.setup
Quelle: setup.py:341
Erstmals aufgetreten: 19:51:06 (1 Vorkommnis)
Zuletzt protokolliert: 19:51:06

Setup failed for custom integration 'stiebel_eltron_isg': Unable to import component: cannot import name 'ModbusParams' from 'modbus_connection._client' (/usr/local/lib/python3.14/site-packages/modbus_connection/_client.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1095, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/stiebel_eltron_isg/__init__.py", line 15, in <module>
    from modbus_connection.pymodbus import connect_tcp
  File "/usr/local/lib/python3.14/site-packages/modbus_connection/pymodbus/__init__.py", line 36, in <module>
    from .._client import (
    ...<6 lines>...
    )
ImportError: cannot import name 'ModbusParams' from 'modbus_connection._client' (/usr/local/lib/python3.14/site-packages/modbus_connection/_client.py). Did you mean: 'ModbusTcpParams'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 341, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1055, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1047, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1095, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/stiebel_eltron_isg/__init__.py", line 15, in <module>
    from modbus_connection.pymodbus import connect_tcp
  File "/usr/local/lib/python3.14/site-packages/modbus_connection/pymodbus/__init__.py", line 36, in <module>
    from .._client import (
    ...<6 lines>...
    )
ImportError: cannot import name 'ModbusParams' from 'modbus_connection._client' (/usr/local/lib/python3.14/site-packages/modbus_connection/_client.py). Did you mean: 'ModbusTcpParams'?
```

### Diagnostics

is not available when the integration is not loaded

### Debug log

```text

```

**Comment by Optic00** [comment]
Thanks for the report. This confirms that integration release 2026.8 is not compatible with Home Assistant 2026.9.0. HA 2026.9 ships the new shared Modbus stack with a newer modbus-connection library, while integration 2026.8 still imports the previous pymodbus adapter. The "blocking call to import_module" warning is a side effect of that failed import, not a separate problem.

PR #672 contains the migration to the shared Modbus stack and raises the minimum HA version to 2026.9.0. It is still a draft while the final stable-release test setup is completed.

Until a compatible integration release is published, the safest option is to restore the backup created before updating Home Assistant, or remain on HA 2026.8.x. Reinstalling integration 2026.8 will not fix the library mismatch.

**Comment by Optic00** [comment]
Correction to my previous comment after testing a separate WPM 3i installation:

Home Assistant was upgraded from 2026.8.3 to 2026.9.0 while integration release 2026.8 remained installed. The integration loaded successfully. All 87 Stiebel-related entities remained present, the same three model-specific entities that were unavailable before the upgrade remained unavailable afterward, and representative operating states, temperatures, setpoints, switches, and cumulative counters remained plausible. The Core log contains neither the `ModbusParams` ImportError nor an integration setup failure.

This does not invalidate the reported failure, but it shows that release 2026.8 is not broken on every HA 2026.9 installation. The traceback may depend on the installed `modbus-connection` package state or the exact upgrade path. It would be useful to compare that environment before treating the incompatibility as universal.

Follow-up: the same installation is now running PR #672 at commit `e6ec21a`. The integration loaded cleanly, retained the same 87 entities and baseline values, successfully handled a same-value write to the hot-water target, and recovered all expected entities after a config-entry reload. No related setup, import, Stiebel, tmodbus, or modbus-connection errors appeared in the checked Core log. A real network interruption and lazy reconnect have not been tested yet.

**Comment by isi07** [comment]
I went back to my backup with the last version of HA 2026.8.3, that is where I upgrade from to 2026.9.0
let me know if I shall provide some more details from my system

I attach the debug information from the HA 2026.8.3. Maybe this gives some insight.

[config_entry-stiebel_eltron_isg-01K8DY3CCXDMX250BVNQFF4GYQ(1).json](https://github.com/user-attachments/files/31756785/config_entry-stiebel_eltron_isg-01K8DY3CCXDMX250BVNQFF4GYQ.1.json)

FYI: I have another TCP Modbus Device, Sungrow inverter, which is connected with custom integration Modbus Manager. Not sure whether this can influence in any way the Modbus connection of Stiebel Eltron ISG integration.

Thanks!

**Comment by Optic00** [comment]
Thanks, this is very useful. The diagnostics confirm Modbus Manager 1.1.5 is installed. It depends on the Home Assistant Modbus integration, which on HA 2026.9 brings `modbus-connection` 4.10.0 into the environment. Stiebel integration 2026.8 still imports the former pymodbus adapter from that package. This makes Modbus Manager the likely trigger for the incompatible package combination in the traceback, even though Sungrow and the ISG use different endpoints.

It also explains why Stiebel 2026.8 loaded on our comparison installation without Modbus Manager. PR #672 removes that old adapter path and uses the HA 2026.9 shared Modbus API, so it is the intended fix. No need to upgrade again just to reproduce this for now; the diagnostics provide the missing comparison point. Thanks for the helpful detail.

**Comment by KlausPallaske** [comment]
"cannot import name 'ModbusParams'"  also here:
```
`2026-09-03 10:05:02.340 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.stiebel_eltron_isg.config_flow',) in /usr/src/homeassistant/homeassistant/loader.py, line 1325: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 203, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 280, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.14/asyncio/base_events.py", line 706, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.14/asyncio/base_events.py", line 677, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.14/asyncio/base_events.py", line 2056, in _run_once
    handle._run()
  File "/usr/local/lib/python3.14/asyncio/events.py", line 94, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 109, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1563, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1617, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1868, in async_create_flow
    handler = await _async_get_flow_handler(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 4232, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 4211, in _load_integration
    await integration.async_get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1128, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1194, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1118, in _load_platforms
    platform_name: self._load_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1293, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1325, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
2026-09-03 10:05:02.343 ERROR (MainThread) [custom_components.stiebel_eltron_isg] Error occurred loading flow for integration stiebel_eltron_isg: cannot import name 'ModbusParams' from 'modbus_connection._client' (/usr/local/lib/python3.14/site-packages/modbus_connection/_client.py)`
```

What else do you need to know?

**Comment by umrath** [comment]
I was too impatient to wait for a fix, so I used an LLM and fixed it for me.
If anyone wants to use it as well: https://github.com/umrath/stiebel_eltron_isg_component

Important: It only works on 2026.9.0 and above. It's explicitely configured to be installable with 2026.8.x already, so you only need one reboot together with upgrading to 2026.9.0 - but if you just reboot without upgrading HA, it will most likely fail to start.

Usual disclaimer: Use at your own risk!

**Comment by Optic00** [comment]
For what it is worth, the official fix is already available as a pre-release: `2026.9-beta1` was published on 2026-09-03 at 08:58 UTC, roughly nine hours before your comment. It includes #672, which drops the old pymodbus adapter path and uses Home Assistant's shared Modbus connection, so it addresses exactly this traceback. You can get it by enabling pre-releases for this integration in HACS.

One difference to your fork: the beta declares `"homeassistant": "2026.9.0"` in `hacs.json`, so it is meant for HA 2026.9 and newer and cannot be staged on 2026.8 for a single combined reboot. Upgrade Home Assistant first, then install the beta.

**Comment by isi07** [comment]
I have installed the beta 1 under HA 2026.9
It looks good. The integration starts and entity values are updated. 
Thanks for the quick fix!

Only observation I have, is a log entry to modbus, but can't tell whether it relates to ISG or the modbus manager integration. 


Logger: pymodbus.logging
Quelle: runner.py:280
Erstmals aufgetreten: 05:30:06 (1 Vorkommnis)
Zuletzt protokolliert: 05:30:06

ERROR: received pdu without a corresponding request, IGNORING

**Comment by Optic00** [comment]
Thanks for confirming. Since the beta loads and updates values on your installation, the reported failure is resolved by `2026.9-beta1` and I am closing this.

On the remaining log line: `received pdu without a corresponding request` comes from pymodbus, and this integration does not go through pymodbus on `2026.9-beta1`. It uses the shared connection from `homeassistant.components.modbus`, which is built on `tmodbus` (`components/modbus/connection.py` in 2026.9). Home Assistant's classic modbus platform is the part that still uses pymodbus, so the line comes from something other than this integration's connection. Which of the pymodbus users on your system produced it, a single startup line cannot say.
