### ISSUE TITLE
2026.7.1 crashes with Modbus Error (5219) and pystiebeleltron 0.6.2 breaks attributes

### ISSUE THREAD

**Issue by torst3n** [pail23/stiebel_eltron_isg_component#603]
When updating the integration to 2026.7.x (which uses `pystiebeleltron` 0.6.1), the integration fails to setup with:

`Failed setup, will retry: input block read at address 5219 (count 12) returned Modbus exception code 2`

This is because older ISGs do not support SG-Ready Register 5219.

If we manually bump `pystiebeleltron` to `0.6.2` (which fixes the modbus crash by making the register optional), the integration fails with:
`AttributeError: 'WpmEnergyData' object has no attribute 'dhw_24h'`

This means the integration code needs to be refactored to support the new data structures in `pystiebeleltron` 0.6.2.

I had to downgrade back to 2026.2 for now.
