### ISSUE TITLE
pystiebeleltron 0.6.3 pins modbus-connection<4, conflicts with HA 2026.9 Fronius (requires >=4.6.1)

### ISSUE THREAD

**Issue by fredericpapaux** [pail23/stiebel_eltron_isg_component#688]
### Before reporting

- [x] I searched the existing issues and discussions
- [x] I am running the latest version of the integration, or I state below why not

### Integration version

2026.8

### Home Assistant version

2026.9.1

### Detected controller

WPM 3i

### Heat pump model

WPM_3i (391)

### What happened, and what did you expect instead

pystiebeleltron 0.6.3 declares modbus-connection[pymodbus]<4,>=3.7.0. Since Home Assistant 2026.9, the core Fronius integration requires fronius-modbus==0.2.0, which needs modbus-connection<5,>=4.6.1. pip resolves this conflict by installing modbus-connection 3.9.0, which breaks both integrations.

The upper bound appears incorrect: with modbus-connection 3.9.0 installed, stiebel_eltron_isg itself fails with ImportError: cannot import name 'ModbusParams' from 'modbus_connection._client'. Did you mean: 'ModbusTcpParams'?

Forcing modbus-connection==4.10.0 (with --no-deps) makes both integrations work correctly.

Errors shown in the HA logs

Setup failed for custom integration 'stiebel_eltron_isg': Unable to import component:
cannot import name 'ModbusParams' from 'modbus_connection._client'
(/usr/local/lib/python3.14/site-packages/modbus_connection/_client.py). Did you mean: 'ModbusTcpParams'?

### Diagnostics

pystiebeleltron 0.6.3 -> modbus-connection[pymodbus]<4,>=3.7.0
fronius-modbus   0.2.0 -> modbus-connection<5,>=4.6.1
flexit-modbus    0.1.0 -> modbus-connection>=4.10.0
sofar-modbus     0.5.0 -> modbus-connection[tmodbus]>=4.7.0

Version of the integration: 2026.8
Home Assistant version: 2026.9.1
Suggested fix: relax the constraint to modbus-connection>=4.6.1,<5 (verified working with 4.10.0).

### Debug log

```text

```

**Comment by pail23** [comment]
The pre-release 2026.9-beta2 should fix this. Can you give it a try?

**Comment by fredericpapaux** [comment]
Sure. I will follow. And many thx for your amazing job!Envoyé de mon iPhoneLe 6 sept. 2026 à 22:11, Paul Frank ***@***.***> a écrit :﻿pail23 left a comment (pail23/stiebel_eltron_isg_component#688)
The pre-release 2026.9-beta2 should fix this. Can you give it a try?

**Comment by Vogelbecker** [comment]
Can confirm, 2026.9-beta2 works for me
HA 2026.9.1 - Tecalor THZ 5.5 - ISG v12.2.3

<img width="1275" height="918" alt="Image" src="https://github.com/user-attachments/assets/c6442338-fb02-4dd3-9688-7b5fa1eebb2c" />

**Comment by fredericpapaux** [comment]
Beta2 ok for me too. No more problem with modbus-connection 4.11.1, keep it in 4.10.0. It’s work! Well done!

**Comment by Optic00** [comment]
Both reports confirm that 2026.9-beta2 resolves the dependency conflict. Closing this as fixed in that prerelease; this does not mean a stable release containing the fix is available yet.
