### ISSUE TITLE
Heat Circuit 3 (values) missing, v2025.7.1 (HA 2025.8.3)

### ISSUE THREAD

**Issue by piersdd** [pail23/stiebel_eltron_isg_component#437]
## Version of the custom_component
 
 HACS component v2025.7.1
 HA version 2025.7.2
 
## Hardware model of the heat pump

Stiebel-Eltron WPL 25
 
|             | Software | Software Version | Major Version | Minor Version | Revision | Build |
| ----------- | -------- | ---------------- | ------------- | ------------- | -------- | ----- |
| Controller  | 449      | 8                |               |               |          |       |
| WPE         | 503      | 3                |               |               |          |       |
| Heat Pump 1 | 393      | 12               |               |               |          |       |
| Heat Pump 2 | 393      | 11               |               |               |          |       |
| ISG         |          |                  | 12            | 2             | 3        | 260   |
 
 
## Describe the bug
Missing values, that were previously exposed: **Heat Circuit 3**
including, missing; 
- number.stiebel_eltron_isg_comfort_temperature_target_hk3
 
Note:
some value/entities are presented for Heat Circuit 3;
- Dew Point Temperature HK 3
- Humidity HK 3
- Eco Temperature Target HK3

## Debug log

diagnostics https://gist.github.com/piersdd/53dd3518d4d856737c529091769729f4

**Comment by Optic00** [comment]
The diagnostics dump in the first post answers this. Short version: the HK3
comfort temperature was read from a register one below the real one, and that is
corrected in pystiebeleltron 0.6, which the integration pins on main but which
is not in a tagged integration release yet.

All addresses below are wire addresses, that is what actually goes out in the
Modbus request, which is the documented address minus one. I verified that offset
on hardware with single register reads against an ISG: 1500 returns the operating
mode (documented 1501), 1501 the comfort temperature HK1, 1509 the DHW comfort
temperature (documented 1510 KOMFORT TEMPERATUR Warmwasser).

**Which registers were read for HK3**

| library | comfort HK3 | eco HK3 | curve rise HK3 |
| --- | --- | --- | --- |
| 0.2.3, 0.5.1 | 1549 | 1550 | 1551 |
| 0.6.0 and 0.6.1 | 1550 | 1551 | 1552 |

(0.2.3 stores documented numbers internally and converts them when reading, 0.5.1
stores wire addresses, so they differ in the source but request the same
registers.)

**What your dump shows.** Its keys are documented addresses, so subtract one for
the wire address. The system parameters were read as one request over wire 1500
to 1551, so every register in that span was requested:

- key 1550, wire 1549: answered with the `0x8000` "value unavailable" sentinel,
  which the library turns into `None`, and the diagnostics of that version drop
  `None` values. That is why there is no entry, and why the HK3 comfort number has
  no value. The same happens to keys 1509 and 1513 to 1519, which likewise come back
  as unavailable.
- key 1551, wire 1550: 20.5, labelled eco temperature HK3
- key 1552, wire 1551: raw content 170, labelled heating curve rise, shown as 1.70

**Why the 0.6 addresses are the right ones.** Read those same two registers as
0.6 does and they become comfort HK3 = 20.5 °C and eco HK3 = 17.0 °C. The 17.0 is
exactly the eco temperature of HK1 and HK2 in your own dump. Under the old
addresses the same raw content had to be read as a heating curve rise of 1.70,
and the register below reported "unavailable", which is what an address the
controller does not implement looks like.

**What that means for you**

- 2026.7-beta3 pins pystiebeleltron 0.5.1, so it still reads the old registers.
- main pins 0.6.1, so the next build should give the HK3 comfort entity a
  plausible value instead of leaving it without one. The entity exists in the
  affected releases too, it just had no value behind it. Expect the eco value to drop from 20.5 to 17.0 at
  the same time, because it was showing the comfort register until now.

I could not test this on HK3 hardware, the machine I have access to is a WPM 3i
with two heating circuits, so a confirmation from one of you after the next
release is what would actually close this.

One caveat for @pail23: 0.6.1 pools the HK3 fields into a single request over
wire 1500 to 1607. If a controller answers an address in that span that it does
not implement with an illegal data address exception instead of the `0x8000`
sentinel, the whole request fails, which fails the coordinator update and takes
every entity of that device down, not just HK3. Worth keeping in mind for reports
where everything goes unavailable at once.

**Comment by Optic00** [comment]
Correction to my comment above: the fix is in a tagged release after all. Release **2026.7** pins `pystiebeleltron==0.6.1`, so the corrected HK3 addresses ship with it, and my remark that it was only on main was out of date when I wrote it.

Closing this as fixed. If HK3 still shows unavailable after updating to 2026.7, please reopen with a fresh diagnostics dump, because then it is a different cause than the register shift analysed here.
