### ISSUE TITLE
cannot import name 'EnergySystemInformationRegisters'

### ISSUE THREAD

**Issue by kizug17** [pail23/stiebel_eltron_isg_component#658]
### Before reporting

- [x] I searched the existing issues and discussions
- [x] I am running the latest version of the integration, or I state below why not

### Integration version

2026.2

### Home Assistant version

2026.8.1

### Detected controller

LWZ

### Heat pump model

LWZ 8 CS Premium

### What happened, and what did you expect instead

After upgrade docker to versions 2026.8.1, it looks pretty similar to issue from 
* https://github.com/pail23/stiebel_eltron_isg_component/issues/648

But this is on version HA 2026.8.1

### Diagnostics

[home-assistant_2026-08-13T06-29-58.537Z.log](https://github.com/user-attachments/files/31016524/home-assistant_2026-08-13T06-29-58.537Z.log)

### Debug log

```text
`2026-08-13 08:29:17.010 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'stiebel_eltron_isg': Unable to import component: cannot import name 'EnergySystemInformationRegisters' from 'pystiebeleltron' (/usr/local/lib/python3.14/site-packages/pystiebeleltron/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1031, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1091, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/stiebel_eltron_isg/__init__.py", line 21, in <module>
    from custom_components.stiebel_eltron_isg.data import (
    ...<2 lines>...
    )
  File "/config/custom_components/stiebel_eltron_isg/data.py", line 10, in <module>
    from .coordinator import StiebelEltronModbusDataCoordinator
  File "/config/custom_components/stiebel_eltron_isg/coordinator.py", line 11, in <module>
    from pystiebeleltron import (
    ...<3 lines>...
    )
ImportError: cannot import name 'EnergySystemInformationRegisters' from 'pystiebeleltron' (/usr/local/lib/python3.14/site-packages/pystiebeleltron/__init__.py). Did you mean: 'EnergySystemInformation'?
`
```

**Comment by Optic00** [comment]
This appears to be the Home Assistant 2026.8 variant of #648. Integration 2026.2 accepts `pystiebeleltron>=0.2.3`, so Core 2026.8.1's pinned `0.5.0` satisfies that requirement. This is consistent with the reported missing `EnergySystemInformationRegisters` export.

Could you first confirm whether Home Assistant's built-in STIEBEL ELTRON integration is also configured? Both integrations share the installed library. Custom release 2026.8 requires `0.6.3`, while Core 2026.8.1 still requires `0.5.0`, so those requirements conflict if both integrations are configured. Alignment through home-assistant/core#178801 is merged but not released yet.

If you only use the custom integration, please update it to release 2026.8 in HACS, perform a full Home Assistant restart, and report whether it loads. Release 2026.2 is not a workaround on Core 2026.8.

**Comment by kizug17** [comment]
My bad, I was using 2026.2. I didn't noticed that there is a new version 😮‍💨 

So after the update to 2026.8, all works like a charm.

Please close this ticket
