### ISSUE TITLE
Since HA 2025.8 Modbus error

### ISSUE THREAD

**Issue by Stefan-83** [pail23/stiebel_eltron_isg_component#421]
Just updated to 2025.8
Unfortunately "Stiebel Eltron ISG" isn't working anymore. Tried to remove/add the device again.

"Failed setup, will retry: ModbusClientMixin.read_input_registers() got an unexpected keyword argument **'slave'**"

<img width="807" height="240" alt="Image" src="https://github.com/user-attachments/assets/95d44e25-b905-4b44-8ee0-65f8bcf1d4a3" />

It seems to be a problem with Modbus. Are there any changes in the latest update?

Thanks

## Version of the custom_component
2025.7.1

**Comment by sommer-nt** [comment]
In the meantime, I deleted the HACS integration of the Stiebel Eltron ISG and tried to get it working again on 2025.7.4. Unfortunately, that failed, as the error popped up again what is really mysteriously. Even with the perfectly working 2025.4.1 (April release) from pail23, I still get the Modbus error. Unfortunately, now I can't integrate the Stiebel Eltron device at all. It looks like the error is deep in the HA core library like @alb-sch mentioned. But I can't identify where exactly the bug is anchored.

**Comment by alb-sch** [comment]
@sommer-nt: as far as I understand the integration is using a package named "pystiebeleltron". When looking into the source code of that very package you find entries like:

__init__.py

                heat_pump_data = await self.read_input_registers(
                    slave=self._slave,
                    address=registerblock.base_address,
                    count=registerblock.count,
                )

the **slave=self.slave** seems to be the problem since it is supposed to be changed into **unit=self.slave** ... adapting that locally isn't really the problem ... it is just work 😉 . But ...

1. how do I install my local changes within Home Assistant?
2. this could only be a temporary workarround ... how to perform a final fix?

**Comment by sommer-nt** [comment]
@alb-sch I'm not a specialist, so unfortunately I can't answer your questions.
Especially since I couldn't find the "pystiebeleltron" package in my integration. 
I looked for it in the custom_components under the stiebel_eltron_isg.

**Comment by jahallam** [comment]
I have encountered the same problem when upgrading to 2025.8
Where can I find the file I need to update?

**Comment by sommer-nt** [comment]
@Djcd Could you please show step by step what you exactly did? I am a bit lost, since I couldn't navigate into the code file where to adjust the certain variables and how to save. Thanks in advance.

**Comment by sommer-nt** [comment]
I got it working again.
It was a bit complicated for me, but it was doable.
I'm happy with the solution for now.
Thanks for the effort @alb-sch @Djcd

**Comment by McJameson** [comment]
@alb-sch Where would I find the files you received from @Djcd ?

**Comment by McJameson** [comment]
Yes, that does help. 
It also looks like @pail23 and @Djcd are in the final stages of getting an update ready for deployment.
I am just not sure how long it will take for the update to make it into the HA repository.

**Comment by timw84** [comment]
> Hi McJameson,
> 
> > > > >
> 
> I am just not sure how long it will take for the update to make it into the HA repository.
> 
> > > > >
> 
> same problem here ... therefor my "quick" solution 😉
> 
> By the way ... just uploaded a tarball of how my stiebel_eltron_isg directory looks like ...
> 
> [stiebel_eltron_isg.tar.gz](https://github.com/user-attachments/files/21682131/stiebel_eltron_isg.tar.gz)
> 
> ... so that you can actually see what I ment with "modify each file having the line pystiebeleltron" ...

@alb-sch  Can i just use this file and copy and replace the files on my HomeAssistant?

**Comment by kaiwoknaj** [comment]
I can confirm, editing in manifest.json

  "pystiebeleltron>=0.2.0"   -> "pystiebeleltron>=0.2.2"

made it work again.

**Comment by pail23** [comment]
Should be fixed in version 2025.8

**Comment by pail23** [comment]
@ehrenhauser In my case an additional restart of homeassistant fixes this issue.

**Comment by ProfGoodspeed** [comment]
> Hello, is version 2025.8 really working for everyone? I now have:
> 
> <img alt="Image" width="1287" height="411" src="https://private-user-images.githubusercontent.com/175529526/476337509-ecb5f59f-a44d-43ac-b029-0d574b84242c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ4MTQ1NTIsIm5iZiI6MTc1NDgxNDI1MiwicGF0aCI6Ii8xNzU1Mjk1MjYvNDc2MzM3NTA5LWVjYjVmNTlmLWE0NGQtNDNhYy1iMDI5LTBkNTc0Yjg0MjQyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgxMFQwODI0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjg1MmRhZGZmOWQzYjRlZGE0NTBlNzExNDgxY2JjMGYxMTM4MjVhMzIwNGVkZmQ4ZmRiNjhkMzU5NzQzMzUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jUA7eVKyHeDI2iZKVt24uWbtkOZ40kj8movPwEpWFX4">
> am I missing something?

Same here.

**Comment by ehrenhauser** [comment]
Also for me still the same after several restarts and reboots.

**Comment by McJameson** [comment]
I have two HA instances running: Development and Production.
Dev was affected by the upgrade to HA 2025.8 with the ISG integration becoming non-functional. Thus, I rolled Dev back to HA 2025.7, with no change: ISG was still broken. When the ISG patch came out I have just updated Dev to HA 2025.8 again and everything is working as s charm now.
In the next step I looked at my Prod and found an update offer for the ISG to take it to 2025.8; the update went perfectly. Then I also updated HA to 2025.8, also with no problems.
In summary, on my two systems the updated ISG integration is working as advertised!
Thanks a lot to the developers for providing an update this quickly!!!

**Comment by chatter80** [comment]
all versions over 2025.4.2-beta2 have the error in HASS 2025.8.0

**Comment by rosenhei64-byte** [comment]
I'm also experiencing a similar issue on my installation. It appears to be a version conflict with the pyModbus library. Initially, my Huawei Solar integration stopped working. After I downgraded Home Assistant to version 2025.7.3, the huawei_solar integration started functioning again, but I'm now getting an error with the stiebel_eltronisg_component.

A related bug report on a change in the pyModbus API can be found in the huawei_solar Issue 1065 : https://github.com/wlcrs/huawei_solar/issues/1065

**Comment by KlausPallaske** [comment]
Good morning.
With 2025.8 I have still the problem:
"Einrichtungsfehler, wird erneut versucht: ModbusClientMixin.read_input_registers() got an unexpected keyword argument 'device_id'"

2025.4.2-beta2 fixes it.

**Comment by KlausPallaske** [comment]
> sorry for asking silly questions: How do I get that and install it? I had help with my HA installation ;) I tried deleting and reinstalling stiebel eltron entity but that didn't fix it

I have had  the integration installed for years and can upgrade and downgrade by selection the version.

**Comment by Silksmooth79** [comment]
Interestingly enough, for me everything seems to be working again with the recent updates:

HAOS: 16.0
HA: 2025.8
Stiebel Eltron: 2025.8

<img width="2246" height="1272" alt="Image" src="https://github.com/user-attachments/assets/24113c06-a43e-4e07-a0e7-3ca720123073" />

**Comment by Schnabulation** [comment]
> Interestingly enough, for me everything seems to be working again with the recent updates:
> 
> HAOS: 16.0 HA: 2025.8 Stiebel Eltron: 2025.8

Could it be a relation between this integration and other integrations using pyModBus? Are you using a Huawei inverter or not? Because I am and I still have the issue with HA 2025.8 and Stiebel Eltron: 2025.8

**Comment by KlausPallaske** [comment]
> > Interestingly enough, for me everything seems to be working again with the recent updates:
> > HAOS: 16.0 HA: 2025.8 Stiebel Eltron: 2025.8
> 
> Could it be a relation between this integration and other integrations using pyModBus? Are you using a Huawei inverter or not? Because I am and I still have the issue with HA 2025.8 and Stiebel Eltron: 2025.8

I'm using an SMA Inverter with the "SMA Solar" Integration.

**Comment by Silksmooth79** [comment]
I am using an E3DC inverter / house power station with my PV installation, which is integrated via a separate protocol in my home assistant instance. So currently only the ISG is using ModBus in my environment.

I am just using an automation triggered by exceeding PV power production to toggle the SG Ready states of the ISG accordingly.

**Comment by SamiiraCat** [comment]
> > sorry for asking silly questions: How do I get that and install it? I had help with my HA installation ;) I tried deleting and reinstalling stiebel eltron entity but that didn't fix it
> 
> Go to HACS search for the Stiebel Eltron Integration, use the three dots to the right, select down load again and there select the mentioned Version…. Hope that helps

in fact that helped a lot :) I never realized I could choose the version there.

Now, error messages change, but still I can't get the integration to start.
Setup failed for custom integration 'stiebel_eltron_isg': Unable to import component: No module named 'pymodbus.framer.base'
Traceback (most recent call last): [followed by a big list - I am ready to copy that too, if it helps]

**Comment by Twiederh** [comment]
In my case there is a Solaredge inverter using Modbus that had issues as well until I reloaded the integration in HACS. Funny enough in my case the whole thing started yesterday morning after I installed the Stiebel Eltron 2025.8.0 integration, even before I upgraded Homeassistant to 2025.8.0. Both the Solaredge Modbus integration and the Stiebel Eltron integration stopped working. During troubleshooting I first did a couple of restarts on the integrations, then I restarted HA, then reinstalled the Solaredge integration. That then worked again but the Stiebel Eltron Integration did not recover even after a reinstall. I then tried upgrading Homeassistant, again reinstalling the Stiebel Eltron Integration and finally got out of the issue by downgrading the to 2025.4.2-beta2

**Comment by dabreese** [comment]
Confirm 2025.4.2-beta2 fixes this also

**Comment by trumpar** [comment]
For me, rollback to Stiebel Eltron Version 2025.7.1 fixed the issue. 😀

**Comment by Twiederh** [comment]
Id did a quick test: I disabled the Solaredge Modbus integration and upgraded the Stiebel Eltron Integration to 2025.8. Unfortunately I had the same error as before, so I downgraded again. This is at least an indicator that the problem might be somewhere else.

**Comment by BauStein-So** [comment]
I updated HA to 2025.8.1 yesterday and I got the same error: „ Einrichtungsfehler, wird erneut versucht: ModbusClientMixin.read_input_registers() got an unexpected keyword argument 'device_id'“
Before it worked Fine with HA 2025.8.0 and Stiebel 2025.8

**Comment by McJameson** [comment]
Try the procedure from @netmikey ; it works very well.

**Comment by SamiiraCat** [comment]
after updating HA OS and HA core today with the newest version (Stiebel Eltron still on  2025.4.2-beta2 ) at last the errors disappeared. Many thanks to everybody who helped!

**Comment by BauStein-So** [comment]
HA 2025.08.2 and Stiebel Eltron 2025.8 is not working 

Logger: homeassistant.setup
Quelle: setup.py:278
Erstmals aufgetreten: 07:03:36 (1 Vorkommnis)
Zuletzt protokolliert: 07:03:36

Setup failed for custom integration 'stiebel_eltron_isg': Requirements for stiebel_eltron_isg not found: ['pystiebeleltron>=0.2.2'].

The workaround with pystiebeleltron==0.2.2 doesn’t work anymore

**Comment by chatter80** [comment]
now with update HASSIO to

<img width="663" height="246" alt="Image" src="https://github.com/user-attachments/assets/ee23624e-d491-4990-9980-8fc31e38e81b" />

is all fine

**Comment by chatter80** [comment]
<img width="1245" height="377" alt="Image" src="https://github.com/user-attachments/assets/81a28bbc-c42a-4ace-8826-6ff84f036701" />

**Comment by michaelherger** [comment]
Could it make a difference whether I was using HAOS or the Container? I'm using the latter (2025.8.2), and the 2025.8 Eltron integration is still broken for me.

**Comment by alb-sch** [comment]
@chatter80 : hi chatter80, had not been following the discussion since quite a while, due to the fact I''d busy with a "SG Ready" interface to our heatpump. This evening I tried upgrading to Core 2025.8.2 ... whole stuff broken again, so I needed to rewind to 2025.8.0 the version, where everything's working fine.
Did you do anything special ... e.g. reinstall Stiebel Eltron ISG?

Here's my configuration:

![Image](https://github.com/user-attachments/assets/abd63a7a-d602-4a7b-a6c5-3d85f9adb041)

Stiebel Eltron ISG version is 2025.7.1


Thanks for your help

**Comment by BauStein-So** [comment]
HAOS 2025.8.3 works fine with Stiebel Eltron ISG 2025.7.1

**Comment by wemi2005** [comment]
And what is with Stiebel Eltron ISG 2025.8 ?

**Comment by nanoBit93** [comment]
@flog123 with the quick fix above or without? I tried ISG 2025.7.1 as well as 2025.8 today, but none of them works with 2025.8.3.

**Comment by basiokan** [comment]
hi same here, i have the same error actually :(

**Comment by trumpar** [comment]
problem seems to be solved ([https://github.com/pail23/stiebel_eltron_isg_component/issues/449](https://github.com/pail23/stiebel_eltron_isg_component/issues/449)) for me at version:
HA:
Core 2025.10.1
Supervisor 2025.10.0
Operating System 16.2 

Tecalor-ISG:
Version 2025.8
